### PR TITLE
fix KeyError when solution is not available

### PR DESCRIPTION
**Pull request by altotin**
was failing due to  KeyError: 'solution'  on any puzzle without answers

e.g. the latest https://www.theguardian.com/crosswords/series/prize

### CODE REVIEW

**Comment by altotin** [comment]
forgot to note,  I tested this locally and got a file which works on squares.io

**Comment by astrojarred** [comment]
Hey thanks so much for the PR and sorry for the long delay. Looks great to me, LGTM!

**Comment by altotin** [comment]
doesn't seem to have made it to  https://astrojarred.github.io/puzzlepull/   still getting an error there

and big thanks to you for making this, we use it multiple times a week

**Comment by astrojarred** [comment]
Thanks for bringing it up-- looks like I'm having trouble with AWS which I use as the backend. Will try to update this as soon as I can.

Glad you're making use of it! If you find any other sites you'd like to have supported just open up an issue :)

**Comment by astrojarred** [comment]
@altotin if you haven't seen let, the the site is [back up and running here](http://sog8ck4.188.34.204.146.sslip.io/)

I played around with a new design as well, and your pull request should be live on there. (From now on any changes should automatically reflect on the site as well.

**Comment by altotin** [comment]
Thanks for the link - I had a quick look but my browser doesn't load javascript over HTTP, trying now today it's offline.

I mainly puzzlepull via a script+wget so if it can continue to have a direct URL to get the file that'd be useful.

**Comment by astrojarred** [comment]
No worries, the API is hosted here now: https://puzzlepull-api.space.jarred.green
and the auto-generated docs are at [\docs](https://puzzlepull-api.space.jarred.green/docs)

The endpoint is still the same so the following should hopefully work:
`https://puzzlepull-api.space.jarred.green/guardian?url=URL&download=false`

Let me know if any issues come up with that!

**Pull request merged**
